<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1" />
<title>Terms and Conditions</title>
<!--[if IE]>
  <link rel="stylesheet" type="text/css" href="all-ie-only.css" />
<![endif]-->
<!--[if !IE]>
  <link rel="stylesheet" type="text/css" href="not-ie.css" />
 <!--<![endif]-->

<!-- Bootstrap Version 3.3.6 -->
<link href="<?php echo base_url(); ?>css/bootstrap.css" rel="stylesheet" type="text/css">
<link href="<?php echo base_url(); ?>css/reset.css" rel="stylesheet" type="text/css" />

<script>
  $(function(){
    var windowHit = $(window).height();
    var heightDiv = $('.divheight').height();
    //console.log(windowHit);
    if(windowHit > heightDiv){
      $('.divheight').css('height',windowHit-78);
    }
    else{
      $('.divheight').css('height',windowHit);
    }
    //
    $('.icon-menu-open').click(function(){
      $('.menu-mobile').slideDown();
      $(this).hide();
      $('.icon-menu-close').show();
    });
    $('.icon-menu-close').click(function(){
      $('.menu-mobile').slideUp();
      $(this).hide();
      $('.icon-menu-open').show();
    });
  });
</script>
<script>
$(document).ready(function(){
  rightFunction();
});
$(window).resize(function(){
  rightFunction();
});
function rightFunction(){
    if($(window).width() < 1200){
    $('.toright').click(function(){
      $('.res-right-side').animate({ 'width' :300 });
      $(this).hide();
      $('.toleft').show();
    });
    $('.toleft').click(function(){
      $('.res-right-side').animate({ 'width' :15 });
      $(this).hide();
      $('.toright').show();
    });
    }
    else{
    $('.res-right-side').css('width', '25%');
    }
}
</script>

<script type="text/javascript">
 document.createElement('header');
 document.createElement('hgroup');
 document.createElement('nav');
 document.createElement('menu');
 document.createElement('section');
 document.createElement('article');
 document.createElement('aside');
 document.createElement('footer');
 document.createElement('figure');
</script>

</head>
<body>

<section class="service-section">
  <div class="container pt30">
    <h1>Conditions of Use for the Online Portal EFynch</h1>
    <h2>GENERAL REMARKS ON HOW IT WORKS</h2>
    <p>Welcome to EFynch – a product of EFynch.Com (“EFynch.Com“).  The following Conditions of Use govern your use of this EFynch website/portal and EFynch via mobile application (collectively, “EFynch Portal”), an Electronic Product, whether to visit the site or register to become a “Designated User” of the EFynch Portal. <strong>If you visit the EFynch Portal, you accept these Conditions of Use</strong>.  These Conditions of Use, as amended from time to time, supplement any terms and conditions in any other agreement.</p>

    <p>EFynch.Com provides this EFynch Portal to Users, free of charge, to solicit bids from Service Professionals for their projects, including, but not limited to, electrical work, plumbing work, landscaping and yard work, hardscaping work, garbage removal, kitchen/bath renovations, roofing work, painting, and other minor and major projects. Users can upload project related information and descriptions for review and bidding by Service Professionals.  The EFynch Portal offers a platform on which Service Professionals can then submit bids and other information to the User to compare.  Service Professionals, pursuant to a separate license agreement, pay a license fee for the use of the EFynch Portal per project, which fee is based upon a percentage of the project value (“Service Professional license fee“).  Once the User selects a Service Professional, EFynch allows the Service Professional and User to easily exchange information regarding the project, including contract documents, drawings, change orders, invoicing, communication and other project documents.   The User does not pay the Service Professional upfront; rather, the following business day after the User and Service Professional enter into a contract for the project, the User escrows the contract amount with EFynch.Com and then directs EFynch.Com when to release funds to the Service Professional during the course of the project.  Users can then submit an assessment of the Service Professional and the Service Professionals can respond to the assessment via the EFynch Portal. EFynch.Com reserves the right to remove any assessments or comments that it deems, in its sole discretion and without recourse or liability to the Service Professional or User, to violate these terms.</p>

    <h3>DEFINITIONS</h3>
    <ul>
      <ol>EFynch.Com – EFynch.Com, its parent, subsidiary and affiliates.</ol>
      <ol>Visitor or You/Your – Any person accessing the EFynch Portal, including Users, Service Professionals, and any corporation, entity or business accessing the EFynch Portal, along with any Designated User registered with the EFynch Portal.</ol>
      <ol>Work or Project – residential and non-residential projects, including electrical work, plumbing work, landscaping and yard work, hardscaping, garbage removal, kitchen/bath renovations, roofing work, painting, and other minor and major projects.</ol>
      <ol>Users or User - Any person who uses the EFynch Portal to post Work in connection with soliciting bids from Service Professionals and/or uses the EFynch Portal for project management, except Service Professional(s) defined below.   The term shall also include anyone visiting this site. Users may include but are not limited to any employees, consultants, contractors and agents, and third parties with which you transact business.</ol>
      <ol>Service Professionals or Service Professional or Contractor – Any person who bids on Work posted by Users on the EFynch Portal and/or uses the EFynch Portal for project management.  The term Service Professionals includes, but is not limited to, tradesmen, laborers, home improvement contractors, handymen, service providers and professionals providing services to Users for Work.  All Service Professionals are independent contractors; no Service Professional is associated, affiliated or employed with EFynch.Com.</ol>
      <ol>EFynch Portal -- The online service residing at https://www.EFynch.Com and available via mobile applications from EFynch.Com to Users, Service Professionals, and Designated Users, including all products, services and features offered via the service, as may be amended from time to time.</ol>
      <ol>Designated Users or Designated User – Any person or entity who create an account to use or access certain parts of the EFynch Portal.</ol>
      <ol>Intellectual Property Rights – These rights include, without limitation, patents, trademarks, trade names, design rights, copyright (including rights in computer software), database rights, rights in know-how and other intellectual property rights, in each case whether registered or unregistered, which may subsist anywhere in the world. The Visitors acknowledge that the Electronic Content and the EFynch Portal and the Intellectual Property Rights contained therein are protected by law. All rights not specifically given to the Designated Users are expressly reserved by EFynch.Com.</ol>
      <ol>Electronic Content - All services and content available in or through the EFynch Portal shall be deemed included within the definition of Electronic Content.   Electronic Content shall include Content uploaded by Users (User Content) or Service Professionals (Service Professional Content).</ol>
    </ul>
    <h3>DISCLAIMERS DIRECT TO USERS</h3>
    <p>Service Professionals are not screened by EFynch.Com.   Service Professionals must register as a Designated User, to bid any Work and, as part of that process, each Service Professional must represent, acknowledge and affirm the following:</p>
    <ul>
      <li><strong>Licensing</strong>. Each Service Professional must acknowledge that it is properly licensed by the State or Local authorities, if applicable, to perform any Work for which it bids. Before accepting any bids, Users should confirm these licensing requirements with the applicable state and local licensing authorities.</li>
      <li><strong>Permits</strong>. Each Service Professional must also acknowledge that it will conform to any requirements regarding permitting and governmental approval <strong>required by the county or local authority in which the Work is being performed. We recommend you confirm these permitting and approval requirements before proceeding with your project. Some states and local authorities hold Users liable for failing to obtain proper permits and governmental approval for Work</strong>.</li>
      <li><strong>Subcontractors or Subcontractor</strong>.   Larger projects often require the use of subcontractors or other trades for specific types of Work. Each Service Professional must acknowledge that it will only subcontract with individuals or companies properly licensed by the State or Local authorities, if applicable, to perform any portion of the Work.  Users should confirm these licensing requirements with the applicable State and Local licensing authorities to verify that all the subcontractors doing Work carry the appropriate licensing.  EFynch.Com cannot verify the licensing status of Service Professionals or subcontractors and relies on the representation of the Service Professionals. </li>
      <li><strong>State Business Filings</strong> – If a Service Professional is a corporation or limited liability company, that Service Professional must acknowledge that it is in good standing in the state in which it is located.  Users should check with the state body governing corporations to confirm this information.</li>
      <li><strong>Criminal Records Search</strong>.  Each Service Professional must also swear that he or she has not been convicted of a serious crime, felony or misdemeanor other than minor traffic violations. EFynch.Com, however, does not perform criminal records searches on Service Professionals.   Users may be able to obtain criminal records searches from third party vendors.  Furthermore, Users may be able to check the Sex Offender Registry of the state in which the Service Professional resides or is in business. EFynch.Com does not run sex offender searches in any states.   Civil and criminal records may also be publicly available in the state in which the Service Professional resides or is in business.</li>
      <li><strong>Qualifications</strong>.  EFynch.Com will take certain steps to bar any Service Professional from the use of the EFynch Portal if EFynch.Com is informed of i) a Service Professional’s false or inaccurate representation, acknowledgment or affirmation related to becoming a Designated User or in connection with the use of the EFynch Portal; or ii) any failure to complete the Work pursuant to industry standards and applicable laws. EFynch.Com makes no guarantees or representations regarding the skills or representations of any Service Professional or the quality of the job that he or she may perform. <strong>EFynch.Com does not endorse, solicit or recommend the services of any Service Professional</strong>. The User is solely responsible to investigate and assess a Service Professional‘s qualifications. EFynch.Com does not negotiate or get involved in the selection or contracting of any Service Professional. The User is solely responsible for selecting and entering into a direct contract or otherwise reach an agreement with a Service Professional. EFynch.Com does not guarantee or warrant any Service Professional‘s performance of the Work. EFynch.Com is not an agent of any Service Professional. Use of the EFynch Portal to obtain bids from Service Professionals or to upload construction documents, including contracts, does not create any contractual relationship between the User and EFynch.Com for the performance of the Work.  The User’s rights are governed by the contractual relationship with the Service Professional selected to perform the Work, and the User agrees that any dispute regarding the performance of the Work will rest solely with the Service Professional and not with EFynch.Com.  You agree that EFynch.Com is not responsible for the accessibility or unavailability of any Service Professional or for your interactions and dealings with any Service Professional, waive the right to bring or assert any claim against EFynch.Com relating to any interactions or dealings with any Service Professional, and release EFynch.Com from any and all liability for or relating to any interactions or dealings with Service Professionals or the Work.</li>
      <li>EFynch.Com is not a contractor and does not provide, arrange for, offer or bid on any Work.  EFynch.Com also will not and does not negotiate or offer to negotiate any contract for any Work.   EFynch.Com is not a contractor, subcontractor, tradesman, salesperson or estimator with respect to any Work.   EFynch.Com provides the EFynch Portal as project management software and bidding solution to Users and Service Professionals.   EFynch.Com is not responsible for the accuracy of the information or Content uploaded by Users or Service Professionals, which are solely responsible for ensuring the accuracy of the information.</li>
    </ul>
    <h3>UPLOADING CONTENT</h3>
    <p>EFynch.Com allows the Service Professional and User to easily exchange information regarding the Work, including contract documents, drawings, change orders, invoicing, communication, photographs and other project documents, information, and content, including personal information such as your name, address and telephone number (collectively, “Content”).   As a condition of uploading any Content to the EFynch Portal, you agree that:</p>
    <ul>
      <ol>You agree that User Content and Service Professional Content will be shared with Service Professionals and Users, respectively. Some User Content will be made available to Service Professionals for bidding purposes.    You agree that by uploading Content, you expressly consent to being contacted by EFynch.Com and by Service Professionals via telephone, facsimile, electronic mail, mail, text (SMS) messaging, or other reasonable means, at any of your contact numbers or addresses, even if you are listed on any federal, state, provincial or other applicable "Do Not Call" list, to address matters pertaining to your Content or Work, including but not limited to marketing related communication. </ol>
      <ol>EFynch.Com has a royalty free, perpetual, irrevocable, worldwide, nonexclusive, transferable, and sublicensable license to use, reproduce, copy, adapt, modify, merge, distribute, publicly display, create derivative works from, incorporate such Content into other works and you grant to EFynch.Com all rights necessary to publish or refrain from publishing your name and address in connection with your Content; sublicense through multiple tiers the Content, and acknowledge that this license cannot be terminated by you once your Content is submitted to the Sites and Services.</ol>
      <ol>You grant to EFynch.Com all rights necessary to prohibit the subsequent aggregation, display, copying, duplication, reproduction, distribution, or exploitation of your Content by any other party.</ol>
      <ol>You represent that you own or have secured all legal rights necessary for the Content submitted by you.</ol>
      <ol>You represent and warrant that each person identified, depicted, or shown in in your Content, if any, (and if a minor, the parent or guardian of the minor) has provided consent to the use of the Content consistent with these Conditions of Use.</ol>
    </ul>
    <h3>CONTENT – USER ASSESSMENTS OF SERVICE PROFESSIONALS & RESPONSES</h3>
    <p>EFynch.Com allows the User to upload or input information regarding the Work performed by the Service Professional, including the quality of the Work and the professionalism of the Service Professional (collectively, “Assessment“) and permits Service Professionals to respond to any Assessment (“Response“).   As a condition of uploading any Assessment or Response to the EFynch Portal, the User and Service Professional agree, respectively, that:</p>
    <ul>
      <ol>His or her Assessment and Response may be made available to the public and to the Service Professionals and Users identified in the Assessment or Response accordingly.</ol>
      <ol>He or she will not submit any Assessments or Responses that may be considered to be infringing, harassing, libelous, abusive, threatening, obscene, profane, hateful, offensive, harmful, vulgar, distasteful, defamatory, or otherwise violates any relevant law or right of any other party, or racially, ethnically or otherwise objectionable.</ol>
      <ol>His or Her Assessment or Response will be accurate, honest, truthful, and complete in all respects and agrees to be solely liable for any Assessments or Response.</ol>
      <ol>A violation of the foregoing could result in significant damages, and the User and Service Professional, respectively, are liable for any such damages, and will indemnify EFynch.Com in the event of any claims based on or arising from your violation of the foregoing.</ol>
      <ol>Assessments and Responses may only be posted regarding projects performed using the EFynch Portal.</ol>
    </ul>
    <h3>PAYMENT FOR WORK – DEPOSIT OF CONTRACT FUNDS WITH EFYNCH.COM</h3>
    <p>The following business day after User and the Service Professional have fully negotiated and executed a written contract for the Work, the User shall then deposit the contract price for the Work with EFynch.Com.  EFynch.Com shall hold the deposit in trust for the User for the payment of the Work.   EFynch.Com shall promptly and no later than seven (7) days from receipt of the same deposit the money in an account that is maintained by EFynch.Com in a financial institution that has one or more branch locations in the State in which the Work is performed and whose deposits are insured by the Federal Deposit Insurance Corporation.   Such account need not be an interest bearing checking or saving account or any combination thereof.  EFynch.Com shall maintain the money in the account until:</p>
    <ul>
      <ol>Directed by the User to pay the Service Professional any whole or part thereof for the Work.</ol>
      <ol>Directed by the User to return the contract price to the User due to a cancellation of the Work, in which case, the contract price shall be returned less any credit card or bank processing fees incurred by EFynch.Com.  EFynch.Com shall also be entitled to withhold that portion of the Service Professional’s License Fee in proportion to the amount paid to the Service Professional for the Work performed.</ol>
      <ol>Directed by the User to return the contract price to the User due to a good-faith dispute regarding the performance of the Service Professional relative to any part of the Work, in which case, the contract price shall be returned less any credit card or bank processing fees incurred by EFynch.Com and EFynch.Com shall retain and hold in trust the Service Professional’s Licensing Fee to be held pending a resolution or settlement of the dispute between Service Professional and the User.  EFynch.Com shall be entitled to that portion of the Service Professional’s License Fee in proportion to the amount paid to the Service Professional  as part of any resolution or settlement, including any judgment.</ol>
      <ol>A Court directs EFynch.Com to distribute the money in a different manner.
        <p>Service Professional and User agree that EFynch.Com shall have the right to offset from any payment to the Service Professional any amounts due by Service Professional to EFynch.Com for Service Professional’s use of the EFynch Portal.</p>
        <p>In the event of any dispute or litigation between User and Service Professional regarding the contract price held by EFynch.Com, User and Service Professional agree that EFynch.Com shall have the option to pay the money into a Court and neither User nor Service Professional has any further right, claim, demand or action against EFynch.Com related to the deposit.  If EFynch.Com elects to pay the money to the User in lieu of the Court, Service Professional has no right, claim, demand or action against EFynch.Com related to the deposit.  Any action for non-payment related to the Work shall rest solely between User and Service Professional, and User and Service Professional each agree to indemnify and defend EFynch.Com from any claim by the other related to the payment of the Work.  In the event EFynch.Com pays the deposit into a court vis-à-vis a interpleader or other action, EFynch.Com shall have the right to deduct from the deposit its filing fees, court costs, service of process fees and attorneys’ fees, provided the amount does not exceed the amount of the deposit.   The forgoing fees, as well as any other fees due EFynch.Com hereunder, may be deducted by EFynch.Com before the money is paid into the Court.   And, if the amount deducted is less than the actual fees incurred by EFynch.Com in that action, then the User and Service Professional agree that the balance may be deducted prior to the payment of the deposit to the User or Service Professional as directed by the Court, as the case may be.</p>
      </ol>
    </ul>
    <h3>OTHER DISCLAIMERS</h3>
    <p>Third parties and Service Professionals may link or otherwise direct Internet users to the EFynch Portal for the purpose of utilizing one or more of the services provided by EFynch.Com. EFynch.Com may provide links or otherwise direct you to third party or Service Professional websites. EFynch.Com does not control or operate any such third party or Service Professional websites. Any information you provide to these third party or Service Professional websites while on these third party or Service Professional websites is subject to the respective policies of those third parties or Service Professional policies. It is your responsibility to review such third party or Service Professional policies, including any relevant privacy policies. You agree that EFynch.Com will not be responsible or liable for, and does not endorse any content, advertising, goods or services provided on or through these outside websites or for your use or inability to use such websites. EFynch.Com does not make any representations or warranties as to the security of any information (including, without limitation, credit card and other personal information) you might be requested to give to any third party or Service Professional sites. You use these third party or Service Professional websites at your own risk.</p>
    <h3>AVAILABILITY OF ELECTRONIC CONTENT</h3>
    <p>EFynch.Com provides Visitors access to Electronic Content via the EFynch Portal.  EFynch.Com reserves the right to either expand or to reduce, at any time, the range Electronic Content made available through the EFynch Portal.  EFynch.Com further reserves the right to change the functions and the manner of functioning of the EFynch Portal and to expand or to supplement the range of services offered therein.</p>
    <p>EFynch.Com makes every effort to adjust and update, punctually and fully, the Electronic Content available on the EFynch Portal.  EFynch.Com, however, is under no legal obligation to adjust or update these items of content or project data, individually or all together, at fixed intervals of time from the date of their being made available onward.  EFynch.Com accepts no liability for the accuracy or timeliness of the Electronic Content of the EFynch Portal.</p>
    <p>EFynch.Com shall (i) use commercially reasonable efforts to make the EFynch Portal available 24 hours a day, 7 days a week, except for: (a) planned downtime (of which we shall give at least 8 hours’ notice via the EFynch Portal, or (b) any unavailability caused by circumstances beyond our reasonable control, including without limitation, acts of God, acts of government, floods, fires, earthquakes, civil unrest, acts of terror, strikes or other labor problems (other than those involving our employees), Internet service provider failures or delays, or denial of service attacks, and (ii) provide access to the EFynch Portal only in accordance with applicable laws and government regulations.</p>
    <p>EFynch.Com shall maintain appropriate administrative, physical, and technical safeguards for protection of the security, confidentiality and integrity of the Content that you upload or enter into the EFynch Portal. EFynch.Com shall not (a) modify your Content or (b) disclose your Content except as set forth herein.</p>
    <h3>COPYRIGHT</h3>
    <p>The Electronic Content of the EFynch Portal, and each article and abstract and all other material available through the EFynch Portal are protected by copyright (unless otherwise indicated on the title page of the article and excepting documents uploaded by Service Professional and User for Work). You have certain rights specified below with respect to Electronic Content; all other rights are reserved.</p>
    <h3>VISITOR RESPONSIBILITIES</h3>
    <p>You shall (i) be responsible for compliance with this Agreement, (ii) be responsible for the accuracy, quality and legality of your Content and of the means by which you acquired your Content, (iii) use commercially reasonable efforts to prevent unauthorized use of the EFynch Portal, and notify EFynch.Com promptly of any such unauthorized use, and (iv) use the EFynch Portal only in accordance with applicable laws and government regulations. You shall not (a) sell, resell, rent or lease the EFynch Portal, (b) use the EFynch Portal to store or transmit infringing, libelous, or otherwise unlawful or tortious material, or to store or transmit material in violation of third-party privacy rights, (c) use the EFynch Portal to store or transmit Malicious Code, (e) interfere with or disrupt the integrity or performance of the EFynch Portal or third-party data contained therein, or (f) attempt to gain unauthorized access to the EFynch Portal or their related systems or networks.</p>
    <h3>GENERAL RULES OF USE</h3>
    <ul>
      <ol>EFynch.Com will require Service Professionals to create an account to use the EFynch Portal, and EFynch.Com may also require Users to create an account to use or access certain parts of the EFynch Portal and use certain products and features (“Designated Users”). EFynch.Com may require that you provide login information such as a username and password to access and utilize your account. As a condition of your use of EFynch Portal, you are responsible for maintaining the confidentiality of any password or other account information not generally available to others and are fully responsible for all activities that occur under your username and password. While there are limited, legitimate reasons for creating multiple accounts, creating serial or overlapping accounts may result in account termination.  Please contact us if you have questions about managing multiple accounts.</ol>
      <ol>Except as provided above or under a separate agreement between you and EFynch.Com, you may not download, copy, distribute, transmit or otherwise reproduce, sell or resell any Electronic Content; nor store any Electronic Content in any form or medium on or in any retrieval system; nor transmit such material, directly or indirectly, for use in any paid service such as document delivery or listserv, nor for use by any information brokerage or for systematic distribution, whether or not for commercial or non-profit use, or for a fee or free of charge. </ol>
      <ol>Except as provided above or under a separate agreement between you and EFynch.Com, you may not use EFynch.Com or any Electronic Content to compete with EFynch.Com or for advertising purposes; and Service Professionals further agree not to solicit business of Users except in response to bids for Work posted by Users on the EFynch Portal and shall not solicit work or contracts from Users without paying or to avoid paying the applicable license fees.</ol>
      <ol>You agree not to remove, obscure or modify any copyright or proprietary notices, author attribution or any disclaimer as they appear on the EFynch Portal. Except as permitted by any applicable license agreement attendant with your registration as a Designated User, you may not integrate Electronic Content with other material, nor otherwise create derivative works in any medium. </ol>
      <ol>You may not do anything to restrict or inhibit any other User's or Service Professional’s access to or use of the EFynch Portal and the Electronic Content.</ol>
      <ol>If you refuse or fail to abide by these Conditions of Use, EFynch.Com reserves the right in its sole discretion to suspend or terminate access to the EFynch Portal and the Electronic Content immediately without notice, in addition to any other available remedies.</ol>
    </ul>
    <h3>RESTRICTIONS</h3>
    <p>Except as otherwise permitted under this Agreement, you may not (a)  use the EFynch Portal access for other than as permitted under this Agreement; (b)  reverse engineer, decompile, or disassemble the EFynch Portal; (c) download, print, copy, circulate, publish, reproduce, or otherwise commercially exploit EFynch.Com information or Electronic Content that is part of or accessible from the EFynch Portal; (d) use the EFynch Portal to send spam or otherwise unlawful email messages or to send or store infringing, obscene, threatening, libelous or otherwise unlawful or tortious material, including material harmful to children or violative of third party privacy rights; (e) use the information or Electronic Content obtained from the EFynch Portal to send or store infringing, obscene, threatening, libelous or otherwise unlawful or tortious material, including material harmful to children or violative of third party privacy rights; (f) knowingly use the EFynch Portal to send or store material containing any harmful computer code; (g) knowingly interfere with or disrupt the integrity or performance of all or any part of the EFynch Portal, (h) attempt to circumvent the security features or otherwise gain unauthorized access to unauthorized portions of the EFynch Portal; (i) modify, copy or create derivative works from any code from the EFynch Portal; or (j) disassemble, reverse engineer, or decompile any code for any part of the EFynch Portal in order to build for non-internal purposes, a product or service that is competitive with the services provided by EFynch.Com.</p>
    <h3>RESERVATION OF RIGHTS/OWNERSHIP</h3>
    <p>ALL RIGHTS IN THE EFYNCH PORTAL NOT EXPRESSLY GRANTED HEREIN ARE RESERVED BY EFYNCH.COM.  The EFynch Portal may be protected by United States and international copyright laws and treaties, as well as patent and other intellectual property laws and treaties.  Except for the rights granted by EFynch.Com in this Agreement, as between the parties, all title, copyright, patent and other proprietary rights, including trade secrets (if any), in and to all copies of the EFynch Portal are owned solely and exclusively by EFynch.Com or its affiliates.</p>
    <p>EFynch.Com reserves the right to store the access history of the Visitor on the EFynch Portal, including, but not limited to, logon history and download/upload history, for a period of time.  EFynch.Com has no obligation to share this access history absent a court order or agreement to do so.</p>
    <h3>EFYNCH.COM LOGO</h3>
    <p>EFynch.Com's logos are a trademark of EFynch.Com. The logo is protected by law and may not be used without EFynch.Com's express written permission. EFynch.Com retains the exclusive right to grant or refuse permission to use its logo.  Any other logos and brand names displayed on the EFynch Portal are the exclusive intellectual property of their respective owners. To the extent applicable, these items are licensed to EFynch.Com but remain the property of their respective owners.</p>
    <h3>ACCURACY OF INFORMATION</h3>
    <p>EFynch.Com reserves the right to correct, change, or update any information on these sites at any time without prior notice.  EFynch.Com is not responsible for any errors, inaccuracies, or incomplete information contained on the EFynch Portal, including any Content uploaded by a User or Service Professional. </p>
    <h3>DISCLAIMER</h3>
    <p>You use the EFynch Portal at your own risk. The materials on the EFynch Portal are provided "as is" and without warranties of any kind, either expressed or implied. To the fullest extent permissible, pursuant to applicable law, EFynch.Com and its affiliates disclaim all warranties of merchantability and fitness for a particular purpose, and of accuracy of informational content. EFynch.Com does not warrant that the functions contained in the EFynch Portal will be uninterrupted or error free, that defects will be corrected, or that it or the server that makes it available are free of viruses or other harmful components.</p>
    <p>EFynch.Com and its employees, directors, officers, agents, vendors, or suppliers will not be liable for any losses or direct, indirect, incidental, consequential, exemplary, or punitive damages arising out of or in connection with the use of or the inability to use the EFynch Portal.</p>
    <p>EFynch.Com is not responsible for any charges associated with accessing the EFynch Portal, including, but not limited to, any computer equipment, telephone or Internet connections and access software.</p>
    <p>EFynch.Com may modify any of these terms and conditions at any time. Your continued use of the EFynch Portal shall be conclusively deemed acceptance of such modifications.</p>
    <p>The EFynch Portal may provide links to third-party websites. Where such links exist, EFynch.Com disclaims all responsibility and liability for the content of such third-party websites. Designated Users assume the sole responsibility for the accessing of third-party websites and the use of any content appearing on them.</p>
    <p>If you are dissatisfied with the EFynch Portal, or with these Conditions of Use, your sole and exclusive remedy is to discontinue using the site.</p>
    <p>EFynch.Com makes no representation or warranty that the EFynch Portal or the information contained therein may be lawfully accessed, transmitted, viewed, downloaded, or otherwise used outside of the United States. Any Designated User accessing the EFynch Portal from outside the United States does so at her or her own risk and is solely responsible for compliance with the laws of the jurisdiction from which access is made.</p>
    <h3>LINKS/SCREEN SHOTS</h3>
    <p>Unauthorized use of images from EFynch.Com websites or the EFynch Portal to create buttons or to highlight links to EFynch.Com is strictly prohibited.  Unauthorized use of screen shots of pages from the EFynch Portal or on other EFynch.Com websites is strictly prohibited, without written permission from EFynch.Com.</p>
    <h3>SECURITY</h3>
    <p>You are prohibited from violating or attempting to violate the security of the EFynch Portal. You may not, directly or indirectly through others: (a) Access data not intended for you or log into a server or account that you are not authorized to access; (b) Attempt to probe, scan, or test the vulnerability of a system or network or to breach security or authentication measures without proper authorization; (c) Attempt to interfere with service to any visitor, host, or network, including, without limitation, submitting a virus, overloading, "flooding," "spamming," "mail bombing," or "crashing"; (d) Send unsolicited email, including promotions or advertising of products or services, to email addresses accessed through the site; (e) Forge any part of the header information in any email or newsgroup posting; (f) Use any device, software, or routine to interfere or attempt to interfere with the proper working of the EFynch Portal, or of any activity conducted on or through the site; or (g) Use or attempt to use any engine, software, tool, agent, or other device or mechanism (including, without limitation, browsers, spiders, robots, avatars, or intelligent agents) to navigate through or search the EFynch Portal.</p>
    <p>Any action that imposes an unreasonable or disproportionately large load on EFynch.Com infrastructure is prohibited.  Violations of system or network security may result in civil or criminal liability. EFynch.Com will investigate such violations and may involve and cooperate with law enforcement authorities in prosecuting visitors who are involved in such violations.</p>
    <h3>TERMINATION OF USE</h3>
    <p>Subject to and in addition to any rights of termination under the License Agreement, EFynch.Com and its representatives reserve the right to deny use of the EFynch Portal or any other EFynch.Com websites to any visitor for any reason without notification. Any violation of the Conditions of Use may result in legal action against the Visitor. EFynch.Com may, in its sole discretion and at any time, modify or terminate the EFynch Portal and remove or refuse to post any information, Content, materials, or other offering.</p>
    <h3>REPRESENTATIONS/WARRANTIES</h3>
    <p>EFynch.Com represents and warrants that (a) the services provided by EFynch.Com hereunder will not violate or infringe any United States registered patent or copyright; (b) EFynch.Com maintains industry standard and protocols and procedures designed to (i) prevent unauthorized access to the <strong>EFynch Portal</strong>, (ii) prevent disabling devices including, but not limited to, codes, commands or instructions that may be used to access, alter, delete, damage or disable the EFynch Portal; and (c) EFynch.Com has not received written notice that the EFynch Portal violates any laws applicable to EFynch.Com’ business. </p>
    <h3>DISCLAIMERS</h3>
    <p>EFYNCH.COM OBTAINS DATA AND CONTENT FROM SOURCES BELIEVED TO BE RELIABLE, BUT ITS ACCURACY AND COMPLETENESS ARE NOT GUARANTEED.  DATA AND CONTENT MAY CONTAIN NONCONFORMITIES, DEFECTS, ERRORS OR OMISSIONS.  THE LIMITED WARRANTY CONTAINED IN THIS TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, EXCEPT FOR THE REPRESENTATIONS AND WARRANTIES  EXPRESSLY MADE ABOVE, YOU DISCLAIM ALL WARRANTIES,  WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE OR ANY PURPOSE, RELIABILITY, ACCURACY, TITLE AND NON-INFRINGEMENT.  YOU ACKNOWLEDGE THAT THE INTERNET IS NOT ALWAYS SECURE AND MAY SOMETIMES GIVE RISE TO SECURITY RISKS.  EXCEPT FOR THE PARTIES’ INDEMNIFICATION OBLIGATIONS AND ANY PAYMENT OBLIGATIONS ARISING FROM THE USE OF EFYNCH PORTAL, NEITHER PARTY SHALL BE LIABLE TO THE OTHER PARTY FOR ANY SPECIAL, INCIDENTAL, INDIRECT, PUNITIVE, EXEMPLARY OR CONSEQUENTIAL DAMAGES ARISING OUT OF THE EFYNCH PORTAL, WHETHER IN AN ACTION OR ARISING OUT OF BREACH OF CONTRACT, TORT OR ANY OTHER CAUSE OF ACTION (SUCH AS THE USE OF OR INABILITY TO USE THE EFYNCH PORTAL AND/OR DATA, OR THE PROVISION OF OR FAILURE TO PROVIDE ANY ATTENDANT SUPPORT SERVICES), EVEN IN THE EVENT OF FAULT, NEGLIGENCE OR MISREPRESENTATION AND EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.</p>
    <p>YOU AGREE THAT EFYNCH.COM IS A PROVIDER OF AN INTERACTIVE COMPUTER SERVICE – THE EFYNCH PORTAL – AND EFYNCH.COM SHALL NOT BE TREATED AS THE PUBLISHER OR SPEAKER OF ANY INFORMATION PROVIDED BY ANY VISITOR OF THE SITE, INCLUDING ANY USER, SERVICE PROFESSIONAL OR THIRD PARTY CONTENT PROVIDER, AND YOU AGREE THAT EFYNCH.COM IS NOT LIABLE FOR ANY SUCH CONTENT EVEN IF AWARE OF ANY OBJECTIONABLE CONTENT. </p>
    <h3>INDEMNIFICATION</h3>
    <p>Visitor shall defend, indemnify and hold EFynch.Com, including its directors, officers, employees and agents, harmless against any damages, losses, liabilities, penalties, fines, demands, judgments, settlements, costs and expenses (including, but not limited to, reasonable attorneys’ fees) arising out of any third party claim relating to the Visitor’s breach or alleged breach of any of its representations, warranties, covenants or obligations under these Conditions of Use or relating to the Visitor‘s failure to comply with any law or regulation applicable to the EFynch Portal, including, but not limited to, any laws governing any Content uploaded or shared by a Visitor, User or Service Professional on the EFynch Portal.</p>
    <h3>PROVISIONS</h3>
    <p>If any provision of these Conditions of Use is held to be invalid, illegal or unenforceable by a court of competent jurisdiction, such provision will be deemed restated, in accordance with applicable law, to reflect as nearly as possible the original intentions of EFynch.Com, and the remainder of the Agreement will remain in full force and effect.</p>
    <h3>ATTORNEY’S FEES</h3>
    <p>In any action or proceeding between Service Professional and User based, in whole or in part, upon the performance or non-performance of the Work or pursuant to any terms and conditions of a contract for the Work between User and Service Professional, including, but not limited to, breach of contract, negligence, misrepresentation or fraud, and EFynch.Com is made a party to such action or proceeding, including, but not limited to, any litigation, arbitration, or complaint and claim before and state administrative body, whether as defendant, cross-defendant, third-party defendant or respondent, User and Service Professional, jointly and severally, agree to indemnify and hold EFynch.Com harmless from and against any and all liability, loss, cost, damages or expenses (including filing fees, court costs, service of process fees, transcript fees and attorneys’ fees) incurred by EFynch.Com in such action or proceeding, providing that such action or proceeding does not result in a judgment against EFynch.Com.  This Paragraph shall apply to any and all such action(s) or proceeding(s) against EFynch.Com including any that are based, in whole or in part, upon any alleged acts or omissions by EFynch.Com, including, but not limited to, any alleged act of misrepresentation, fraud, non-disclosure, negligence, violation of any statutory or common law duty, or breach of fiduciary duty by EFynch.Com.</p>
  </div>
  </section>

  </body>
</html>
